### ISSUE TITLE
@jsx React.DOM has been deprecated => error

### ISSUE THREAD

**Issue by klassm** [securingsincity/react-ace#26]
node_modules/react-ace/src/ace.jsx: Line 1: The @jsx React.DOM pragma has been deprecated as of React 0.12

> 1 | /** @jsx React.DOM */
    | ^
  2 | 
  3 | var ace = require('brace');
  4 | var React = require('react');
    at File.errorWithNode (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:488:13)
    at NodePath.visitor.Program (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/transformers/other/react.js:56:20)
    at NodePath.call (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/traversal/path/context.js:61:28)
    at NodePath.visit (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/traversal/path/context.js:94:8)
    at TraversalContext.visitSingle (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/traversal/context.js:112:12)
    at TraversalContext.visit (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/traversal/context.js:124:19)
    at Function.traverse.node (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/traversal/index.js:72:17)
    at Object.traverse [as default] (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/traversal/index.js:55:14)
    at PluginPass.transform (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/plugin-pass.js:44:27)
    at File.transform (/home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:596:12)
    at /home/klassm/IdeaProjects/react-test/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/pipeline.js:131:19
 @ ./~/react-ace/index.js 5:17-41

**Comment by andrerpena** [comment]
+1, this should be fixed

**Comment by zallek** [comment]
+1 need to be fixed

**Comment by andrerpena** [comment]
@zallek , in case you don't know, this repo has it fixed. It also is exported in ES5 which is the standard: https://github.com/eccenca/react-ace-wrapper

**Comment by klassm** [comment]
But the artifact you get using npm is this repo, isn't it?

**Comment by andrerpena** [comment]
For the fixed version it would be `npm install react-ace-wrapper`. It's another repository.. not `react-ace`. `react-ace` is great but it doesn't export ES5 and has this `React.DOM has been deprecated` bug.

**Comment by securingsincity** [comment]
This should be fixed in 2.0.2

**Comment by andrerpena** [comment]
great to hear that!
